nymea-app: fix DEPENDS on nymea(d)
The dependency at build time must refer to the recipe, not a package.

This fixes:

-8<---------
  ERROR: Nothing PROVIDES 'nymead' (but .../meta-nymea/recipes-nymea ↵
    /nymea-app/nymea-app_git.bb DEPENDS on or otherwise requires it). ↵
    Close matches:
    neard
    nymea
    nymea RPROVIDES nymead
  ERROR: Required build target 'nymea-app' has no buildable providers.
  Missing or unbuildable dependency chain was: ['nymea-app', 'nymead']
-8<---------

Fixes: e4a80a0 ("Rework packaging and update recepies")
Signed-off-by: Michael Heimpold <mhei@heimpold.de>
Reviewed-by: Quentin Schulz <quentin.schulz@cherry.de>